import { Router, type IRouter } from "express";
import healthRouter from "./health";
import roomsRouter from "./rooms";
import meetingsRouter from "./meetings";
import authRouter from "./auth";
import tasksRouter from "./tasks";
import analyticsRouter from "./analytics";
import teamsRouter from "./teams";
import usersRouter from "./users";
import adminRouter from "./admin";
import participantsRouter from "./participants";
import recordingsRouter from "./recordings";
import aiRouter from "./ai";
import messagesRouter from "./messages";
import channelsRouter from "./channels";
import filesRouter from "./files";
import notificationsRouter from "./notifications";
import organizationsRouter from "./organizations";
import membersRouter from "./members";
import projectsRouter from "./projects";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use(roomsRouter);
router.use(meetingsRouter);
router.use(tasksRouter);
router.use("/analytics", analyticsRouter);
router.use(teamsRouter);
router.use("/users", usersRouter);
router.use("/admin", adminRouter);
router.use(participantsRouter);
router.use(recordingsRouter);
router.use(aiRouter);
router.use("/messages", messagesRouter);
router.use("/channels", channelsRouter);
router.use("/files", filesRouter);
router.use("/notifications", notificationsRouter);
router.use(organizationsRouter);
router.use(membersRouter);
router.use(projectsRouter);

export default router;
